- name: Run Terraform with Ansible
  hosts: localhost
  tasks:

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: "/terraform-aws-ec2/"

    - name: Plan Terraform Deployment
      command: terraform plan -out=tfplan
      args:
        chdir: "/terraform-aws-ec2/"

    - name: Apply Terraform Deployment
      command: terraform apply -auto-approve tfplan
      args:
        chdir: "/terraform-aws-ec2/"
