- name: Run Terraform Plan
  hosts: all
  gather_facts: no
  tasks:
    - name: Initialize Terraform
      shell: hostname
      register: out

    - name: Display Output
      debug:
        msg: "{{ out.stdout }}"

      

 
