- name: Run Terraform Plan
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize Terraform
      shell: "ifconfig"
      register: out

    - name: Display Output
      debug:
        msg: "{{ out.stdout }}"

      

 
