- name: Run Terraform Plan
  hosts: awx
  tasks:
    - name: Initialize Terraform
      command: terraform --version
      register: out

    - name: Display Output
      debug:
        msg: "{{ out.stdout_lines }}"

      

 
