- name: List Files and Echo Message
  hosts: localhost
  tasks:
    - name: List all files in the current directory
      shell: "ls -lah"
      register: files_list

    - name: Display the list of files
      debug:
        msg: "{{ files_list.stdout_lines }}"

    - name: Echo a message
      shell: "echo 'Hello, this is an Ansible playbook running with Bash!'"
      register: echo_output

    - name: Display echo output
      debug:
        msg: "{{ echo_output.stdout }}"
