- name: Check CPU and Memory Utilization
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CPU Utilization
      shell: "hostname"
      register: cpu_usage
      args:
        executable: /bin/bash

    - name: Display CPU Usage
      debug:
        msg: "{{ cpu_usage.stdout_lines }}"

    - name: Get Memory Utilization
      shell: echo "hi"
      register: memory_usage
      args:
        executable: /bin/bash

    - name: Display Memory Usage
      debug:
        msg: "{{ memory_usage.stdout_lines }}"


      

 
