- name: Check CPU and Memory Utilization
  hosts: ansible
  gather_facts: no
  tasks:
    - name: Get CPU Utilization
      command: top -b -n1 | grep "Cpu(s)"
      register: cpu_usage

    - name: Display CPU Usage
      debug:
        msg: "{{ cpu_usage.stdout_lines }}"

    - name: Get Memory Utilization
      command: free -h
      register: memory_usage

    - name: Display Memory Usage
      debug:
        msg: "{{ memory_usage.stdout_lines }}"


      

 
