- name: Run Terraform Plan
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize Terraform
      shell: "/usr/bin/terraform/terraform --version"
      register: out

    - name: Display Output
      debug:
        msg: "{{ out.stdout }}"

      

 
