- name: Check CPU and Memory Utilization
  hosts: all
  gather_facts: no
  tasks:
    - name: Get CPU Utilization
      shell: ls
      register: cpu_usage

    - name: Display CPU Usage
      debug:
        msg: "{{ cpu_usage.stdout_lines }}"

    - name: Get Memory Utilization
      shell: echo "hi"
      register: memory_usage

    - name: Display Memory Usage
      debug:
        msg: "{{ memory_usage.stdout_lines }}"


      

 
