- name: Run Terraform Plan
  hosts: localhost
  tasks:
    - name: Initialize Terraform
      command: /usr/bin/terraform/terraform --version
      register: out

    - name: Display Output
      debug:
        msg: "{{ out.stdout_lines }}"

      

 
