- name: Run Terraform Plan
  hosts: localhost
  tasks:
    - name: Initialize Terraform
      command: echo "hi "
      register: out

    - name: Display Output
      debug:
        msg: "{{ out.stdout_lines }}"

      

 
